export const UPDATE_SELECTED_DATA = 'UPDATE_SELECTED_DATA';
export const REMOVE_LAST_SELECTED_DATA = 'REMOVE_LAST_SELECTED_DATA';
export const RESET_DATA = 'RESET_DATA';
export const SUBMIT_DATA = 'SUBMIT_DATA';
export const HANDLE_SUBMIT_SUCCESS = 'HANDLE_SUBMIT_SUCCESS';
export const HANDLE_SUBMIT_ERROR = 'HANDLE_SUBMIT_ERROR';
